#!/usr/bin/env python3
"""Convert Helm factory presets (.helm JSON) to C++ arrays for the Twytch engine.

Reads the Helm factory preset bank (from mtytel/helm 'patches/Factory Presets')
and emits machine/Twytch/twytch_factory_patches.h/.cpp. Each preset's settings
dict and modulations array are stored verbatim (native units, matching the
HelmEngine control values) so a patch can be applied at load time.

Usage:
  convert_helm_presets.py <factory_presets_dir> <out_dir>
"""

import json
import os
import sys


def main():
    src_dir = sys.argv[1] if len(sys.argv) > 1 else "patches/Factory Presets"
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "machine/Twytch"

    files = []
    for root, _, names in os.walk(src_dir):
        for n in names:
            if n.endswith(".helm"):
                files.append(os.path.join(root, n))
    files.sort()

    patches = []
    for path in files:
        with open(path) as f:
            data = json.load(f)
        settings_obj = data.get("settings", {})
        modulations = settings_obj.get("modulations", [])
        settings = [(k, v) for k, v in settings_obj.items() if k != "modulations"]
        patches.append({
            "name": data.get("patch_name", os.path.splitext(os.path.basename(path))[0]),
            "folder": data.get("folder_name", ""),
            "author": data.get("author", ""),
            "settings": settings,
            "modulations": [(m.get("source", ""), m.get("destination", ""), m.get("amount", 0.0))
                            for m in modulations],
        })

    header = (
        "// Auto-generated by tools/convert_helm_presets.py\n"
        "// Helm factory preset bank (c) respective patch authors; see each preset's\n"
        "// 'license' field / the LICENSES file in the Helm repository.\n"
        "#ifndef TWYTCH_FACTORY_PATCHES_H_\n"
        "#define TWYTCH_FACTORY_PATCHES_H_\n"
        "\n"
        "namespace twytch {\n"
        "\n"
        "struct FactorySetting {\n"
        "  const char* name;\n"
        "  float value;\n"
        "};\n"
        "\n"
        "struct FactoryModulation {\n"
        "  const char* source;\n"
        "  const char* destination;\n"
        "  float amount;\n"
        "};\n"
        "\n"
        "struct FactoryPatch {\n"
        "  const char* name;\n"
        "  const char* folder;\n"
        "  const char* author;\n"
        "  const FactorySetting* settings;\n"
        "  int num_settings;\n"
        "  const FactoryModulation* modulations;\n"
        "  int num_modulations;\n"
        "};\n"
        "\n"
        f"extern const FactoryPatch kFactoryPatches[{len(patches)}];\n"
        f"extern const char* const kFactoryPatchNames[{len(patches)}];\n"
        "extern const int kNumFactoryPatches;\n"
        "\n"
        "}  // namespace twytch\n"
        "\n"
        "#endif  // TWYTCH_FACTORY_PATCHES_H_\n"
    )

    lines = []
    lines.append("// Auto-generated by tools/convert_helm_presets.py")
    lines.append("#include \"twytch_factory_patches.h\"")
    lines.append("")
    lines.append("namespace twytch {")
    lines.append("")

    def fmt_float(v):
        s = repr(float(v))
        if 'e' in s or 'E' in s:
            s = '%.10g' % v
        return s

    # Emit flat arrays of settings and modulations, then the patches.
    settings_offset = []
    mods_offset = []
    for p in patches:
        settings_offset.append(len(lines))
        lines.append("static const FactorySetting %s[] = {" % ("s" + str(len(settings_offset) - 1)))
        for name, value in p["settings"]:
            name = name.replace('"', '\\"')
            lines.append('  { "%s", %sf },' % (name, fmt_float(value)))
        lines.append("};")
        lines.append("")

        mods_offset.append(len(lines))
        lines.append("static const FactoryModulation %s[] = {" % ("m" + str(len(mods_offset) - 1)))
        for src, dst, amt in p["modulations"]:
            src = src.replace('"', '\\"')
            dst = dst.replace('"', '\\"')
            lines.append('  { "%s", "%s", %sf },' % (src, dst, fmt_float(amt)))
        lines.append("};")
        lines.append("")

    lines.append(f"const FactoryPatch kFactoryPatches[{len(patches)}] = {{")
    for i, p in enumerate(patches):
        name = p["name"].replace('"', '\\"')
        folder = p["folder"].replace('"', '\\"')
        author = p["author"].replace('"', '\\"')
        lines.append("  {")
        lines.append(f'    "{name}", "{folder}", "{author}",')
        lines.append(f"    s{i}, {len(p['settings'])}, m{i}, {len(p['modulations'])},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append(f"const char* const kFactoryPatchNames[{len(patches)}] = {{")
    for p in patches:
        name = p["name"].replace('"', '\\"')
        lines.append(f'  "{name}",')
    lines.append("};")
    lines.append("")
    lines.append("const int kNumFactoryPatches = %d;" % len(patches))
    lines.append("")
    lines.append("}  // namespace twytch")
    lines.append("")

    with open(os.path.join(out_dir, "twytch_factory_patches.h"), "w") as f:
        f.write(header)
    with open(os.path.join(out_dir, "twytch_factory_patches.cpp"), "w") as f:
        f.write("\n".join(lines))

    total_settings = sum(len(p["settings"]) for p in patches)
    total_mods = sum(len(p["modulations"]) for p in patches)
    print(f"Converted {len(patches)} patches ({total_settings} settings, {total_mods} modulations)")
    print(f"Wrote {out_dir}/twytch_factory_patches.h and twytch_factory_patches.cpp")


if __name__ == "__main__":
    main()
