// Auto-generated by tools/convert_helm_presets.py
// Helm factory preset bank (c) respective patch authors; see each preset's
// 'license' field / the LICENSES file in the Helm repository.
#ifndef TWYTCH_FACTORY_PATCHES_H_
#define TWYTCH_FACTORY_PATCHES_H_

namespace twytch {

struct FactorySetting {
  const char* name;
  float value;
};

struct FactoryModulation {
  const char* source;
  const char* destination;
  float amount;
};

struct FactoryPatch {
  const char* name;
  const char* folder;
  const char* author;
  const FactorySetting* settings;
  int num_settings;
  const FactoryModulation* modulations;
  int num_modulations;
};

extern const FactoryPatch kFactoryPatches[274];
extern const char* const kFactoryPatchNames[274];
extern const int kNumFactoryPatches;

}  // namespace twytch

#endif  // TWYTCH_FACTORY_PATCHES_H_
