// Auto-generated by tools/convert_patches.py
// Ambika softsynth patch bank — converted from Shruthi-1 format
#ifndef AMBIKA_PATCHES_H_
#define AMBIKA_PATCHES_H_

#include "common/patch.h"

namespace ambika {

extern const Patch kPatches[208];
extern const char* const kPatchNames[208];
extern const int kNumPatches;

}  // namespace ambika

#endif  // AMBIKA_PATCHES_H_